###############################################
### Users
###############################################

### User Registration
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "name": "test",
  "email": "test@aol.com",
  "password": "test"
}


### User Login

POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "test@aol.com",
  "password": "test"
}

# @token = PUT_ACCESS_TOKEN_HERE

###############################################
### SURVEYS
###############################################

### Get All Surveys For User
GET http://localhost:8000/api/survey

### Get Single Survey
GET http://localhost:8000/api/survey/id

### Create Survey
POST http://localhost:8000/api/survey
Content-Type: application/json

{
  "name": "Survey 1",
  "description": "Cool survey, bro!"
}

### Update Survey
PUT http://localhost:8000/api/survey/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Deno Fail",
  "description": "Cool stuff"
}

### Delete the survey
DELETE http://localhost:8000/api/survey/5eddbe7900458e0100542d8c
Authorization: Bearer {{token}}
